---
- name: Download client binary
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ ansible_system }}_{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.bz2"
    dest: '/tmp/'
  register: get_url_restic

- name: Decompress the binary
  shell: bzip2 -dc {{ get_url_restic.dest }} > {{ restic_install_path }}/restic
  args:
    creates: '{{ restic_install_path }}/restic'

- name: Ensure permissions are correct
  file:
    path: '{{ restic_install_path }}/restic'
    mode: '0755'
    owner: 'root'
    group: 'root'
