---
- name: Ensure restic group is present
  group:
    name: "{{ restic_group }}"
    system: yes

- name: Ensure restic user is present
  user:
    name: "{{ restic_user }}"
    group: "{{ restic_group }}"
    shell: /bin/false
    system: yes
    createhome: false
    state: present
  when: restic_user != 'root'

- name: Ensure restic installation directory exist
  file:
    state: 'directory'
    path: '{{ restic_install_path }}'

- name: Download client binary
  become: no
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.bz2"
    dest: '/tmp'
  delegate_to: localhost
  run_once: true

- name: Decompress the binary
  become: no
  shell: "bzip2 -dc /tmp/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.bz2 > /tmp/restic"
  args:
    creates: "/tmp/restic"
  delegate_to: localhost
  run_once: true

- name: Propagate restic binary
  copy:
    src: /tmp/restic
    dest: '{{ restic_install_path }}/restic'
    mode: '0750'
    owner: 'root'
    group: '{{ restic_group }}'

- name: Set proper capabilities for restic binary
  capabilities:
    path: '{{ restic_install_path }}/restic'
    capability: cap_dac_read_search+ep
    state: present
