---
- name: Download client binary
  become: no
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ ansible_system }}_{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.bz2"
    dest: '/tmp'
  delegate_to: localhost
  run_once: true

- name: Decompress the binary
  become: no
  shell: "bzip2 -dc /tmp/restic_{{ ansible_system }}_{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.bz2 > /tmp/restic"
  args:
    creates: "/tmp/restic"
  delegate_to: localhost
  run_once: true

- name: Propagate restic binary
  copy:
    src: /tmp/restic
    dest: '{{ restic_install_path }}/restic'
    mode: '0755'
    owner: 'root'
    group: 'root'
