---

- name: Set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux_amd64'
  when: ansible_userspace_bits == '64'

- name: Set internal variable platform-suffix
  set_fact:
    _platform_suffix: 'linux_386'
  when: ansible_userspace_bits == '32'

- name: Download client binary
  become: no
  get_url:
    url: '{{ restic_url }}'
    dest: '/tmp/restic.bz2'
  delegate_to: localhost
  run_once: true

- name: Decompress the binary
  become: no
  shell: bzip2 -dc /tmp/restic.bz2 > /tmp/restic
  args:
    creates: '{{ restic_install_path }}/restic'
  delegate_to: localhost
  run_once: true

- name: Propagate restic binary
  copy:
    src: /tmp/restic
    dest: '{{ restic_install_path }}/restic'
    mode: '0755'
    owner: 'root'
    group: 'root'
